openapi: 3.0.1
info:
  title: STD24117
  description: This is a specification of STD24117
  version: 1.0.0
servers:
  - url: 'https://localhost:8000'
paths:
  /ping:
    get:
      description: pong
      responses:
         "200":
  /cars:
    /post:
      description: creer une liste de l'object
      responses:
       "200":
         param:
           -id
           -brand
           -model
    /get:
      description: liste de l'object
      responses:
        "200":
          shema:
            type: array
















  
